spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TOWN_PORTAL
    username: root
    password: 81868936
  jpa:
    hibernate:
      ddl-auto: create-drop
  freemarker:
    expose-request-attributes: true